import { Semester, StudentProfile } from '../types';

export const INITIAL_STUDENT_PROFILE: StudentProfile = {
  name: 'Nguyễn Văn Tùng',
  studentId: '2021-VNU-IT042',
  university: 'Đại Học Quốc Gia (VNU)',
  major: 'Công nghệ Thông tin & Khoa học Dữ liệu',
  classCohort: 'K66-CNTT',
  startYear: 2021,
  totalProgramCredits: 140,
  targetCpa: 3.6,
  academicStandingNote: 'Sinh viên năm 4 - Dự kiến tốt nghiệp loại Xuất sắc',
};

export const INITIAL_SEMESTERS_DATA: Semester[] = [
  {
    id: 'sem-y1s1',
    year: 1,
    term: 1,
    name: 'Học kỳ 1 - Năm 1',
    shortName: 'HK1 - Y1',
    academicYear: '2021 - 2022',
    isCompleted: true,
    targetGpa: 3.5,
    subjects: [
      { id: 's-101', code: 'MAT1091', name: 'Giải tích 1', credits: 3, score10: 8.8, scoreLetter: 'A', score4: 3.8, category: 'daicuong' },
      { id: 's-102', code: 'MAT1092', name: 'Đại số tuyến tính', credits: 3, score10: 8.2, scoreLetter: 'B+', score4: 3.5, category: 'daicuong' },
      { id: 's-103', code: 'INT1004', name: 'Nhập môn Lập trình C/C++', credits: 4, score10: 9.2, scoreLetter: 'A+', score4: 4.0, category: 'coso' },
      { id: 's-104', code: 'ENG1001', name: 'Tiếng Anh học thuật 1', credits: 4, score10: 8.0, scoreLetter: 'B+', score4: 3.5, category: 'daicuong' },
      { id: 's-105', code: 'PHI1006', name: 'Triết học Mác - Lênin', credits: 3, score10: 7.8, scoreLetter: 'B', score4: 3.0, category: 'daicuong' },
    ],
  },
  {
    id: 'sem-y1s2',
    year: 1,
    term: 2,
    name: 'Học kỳ 2 - Năm 1',
    shortName: 'HK2 - Y1',
    academicYear: '2021 - 2022',
    isCompleted: true,
    targetGpa: 3.7,
    subjects: [
      { id: 's-201', code: 'MAT1093', name: 'Giải tích 2', credits: 3, score10: 8.5, scoreLetter: 'A', score4: 3.8, category: 'daicuong' },
      { id: 's-202', code: 'INT2202', name: 'Lập trình Hướng đối tượng (OOP)', credits: 4, score10: 9.5, scoreLetter: 'A+', score4: 4.0, category: 'coso' },
      { id: 's-203', code: 'INT2204', name: 'Cấu trúc Dữ liệu & Giải thuật', credits: 4, score10: 9.0, scoreLetter: 'A+', score4: 4.0, category: 'coso' },
      { id: 's-204', code: 'PHY1100', name: 'Vật lý đại cương', credits: 3, score10: 8.4, scoreLetter: 'B+', score4: 3.5, category: 'daicuong' },
      { id: 's-205', code: 'ENG1002', name: 'Tiếng Anh học thuật 2', credits: 4, score10: 8.6, scoreLetter: 'A', score4: 3.8, category: 'daicuong' },
    ],
  },
  {
    id: 'sem-y2s1',
    year: 2,
    term: 1,
    name: 'Học kỳ 1 - Năm 2',
    shortName: 'HK1 - Y2',
    academicYear: '2022 - 2023',
    isCompleted: true,
    targetGpa: 3.6,
    subjects: [
      { id: 's-301', code: 'INT2208', name: 'Kiến trúc máy tính & Vi xử lý', credits: 3, score10: 8.3, scoreLetter: 'B+', score4: 3.5, category: 'coso' },
      { id: 's-302', code: 'INT2215', name: 'Cơ sở Dữ liệu & Hệ quản trị CSDL', credits: 4, score10: 9.1, scoreLetter: 'A+', score4: 4.0, category: 'chuyennganh' },
      { id: 's-303', code: 'MAT2301', name: 'Xác suất Thống kê ứng dụng', credits: 3, score10: 8.7, scoreLetter: 'A', score4: 3.8, category: 'daicuong' },
      { id: 's-304', code: 'INT2209', name: 'Mạng máy tính & Truyền thông', credits: 3, score10: 8.0, scoreLetter: 'B+', score4: 3.5, category: 'chuyennganh' },
      { id: 's-305', code: 'POL1001', name: 'Kinh tế chính trị Mác - Lênin', credits: 2, score10: 8.0, scoreLetter: 'B+', score4: 3.5, category: 'daicuong' },
      { id: 's-306', code: 'PES1001', name: 'Giáo dục thể chất 1', credits: 1, score10: 9.0, scoreLetter: 'A+', score4: 4.0, category: 'khac' },
    ],
  },
  {
    id: 'sem-y2s2',
    year: 2,
    term: 2,
    name: 'Học kỳ 2 - Năm 2',
    shortName: 'HK2 - Y2',
    academicYear: '2022 - 2023',
    isCompleted: true,
    targetGpa: 3.8,
    subjects: [
      { id: 's-401', code: 'INT3201', name: 'Hệ điều hành (Operating Systems)', credits: 3, score10: 9.4, scoreLetter: 'A+', score4: 4.0, category: 'coso' },
      { id: 's-402', code: 'INT3306', name: 'Công nghệ phần mềm & Agile', credits: 3, score10: 9.0, scoreLetter: 'A+', score4: 4.0, category: 'chuyennganh' },
      { id: 's-403', code: 'INT3307', name: 'An toàn & Bảo mật thông tin', credits: 3, score10: 8.5, scoreLetter: 'A', score4: 3.8, category: 'chuyennganh' },
      { id: 's-404', code: 'INT3308', name: 'Lập trình Web nâng cao (React/Node)', credits: 3, score10: 9.8, scoreLetter: 'A+', score4: 4.0, category: 'tuchon' },
      { id: 's-405', code: 'SOC1001', name: 'Chủ nghĩa xã hội khoa học', credits: 2, score10: 8.1, scoreLetter: 'B+', score4: 3.5, category: 'daicuong' },
      { id: 's-406', code: 'PES1002', name: 'Giáo dục thể chất 2', credits: 1, score10: 9.0, scoreLetter: 'A+', score4: 4.0, category: 'khac' },
    ],
  },
  {
    id: 'sem-y3s1',
    year: 3,
    term: 1,
    name: 'Học kỳ 1 - Năm 3',
    shortName: 'HK1 - Y3',
    academicYear: '2023 - 2024',
    isCompleted: true,
    targetGpa: 3.8,
    subjects: [
      { id: 's-501', code: 'INT3401', name: 'Trí tuệ nhân tạo (AI & Machine Learning)', credits: 4, score10: 9.2, scoreLetter: 'A+', score4: 4.0, category: 'chuyennganh' },
      { id: 's-502', code: 'INT3402', name: 'Điện toán đám mây & DevOps', credits: 3, score10: 8.8, scoreLetter: 'A', score4: 3.8, category: 'chuyennganh' },
      { id: 's-503', code: 'INT3405', name: 'Thiết kế giao diện UI/UX', credits: 3, score10: 9.5, scoreLetter: 'A+', score4: 4.0, category: 'tuchon' },
      { id: 's-504', code: 'HIS1001', name: 'Lịch sử Đảng Cộng sản Việt Nam', credits: 2, score10: 8.2, scoreLetter: 'B+', score4: 3.5, category: 'daicuong' },
      { id: 's-505', code: 'INT3410', name: 'Dự án Công nghệ Thông tin 1', credits: 3, score10: 9.6, scoreLetter: 'A+', score4: 4.0, category: 'chuyennganh' },
    ],
  },
  {
    id: 'sem-y3s2',
    year: 3,
    term: 2,
    name: 'Học kỳ 2 - Năm 3',
    shortName: 'HK2 - Y3',
    academicYear: '2023 - 2024',
    isCompleted: true,
    targetGpa: 3.9,
    subjects: [
      { id: 's-601', code: 'INT3501', name: 'Phân tích dữ liệu lớn (Big Data)', credits: 3, score10: 9.0, scoreLetter: 'A+', score4: 4.0, category: 'chuyennganh' },
      { id: 's-602', code: 'INT3502', name: 'Xử lý ngôn ngữ tự nhiên (NLP & LLMs)', credits: 3, score10: 9.4, scoreLetter: 'A+', score4: 4.0, category: 'tuchon' },
      { id: 's-603', code: 'INT3505', name: 'Thực tập doanh nghiệp (Internship)', credits: 4, score10: 9.7, scoreLetter: 'A+', score4: 4.0, category: 'thuctap_khoaluan' },
      { id: 's-604', code: 'HOC1001', name: 'Tư tưởng Hồ Chí Minh', credits: 2, score10: 8.3, scoreLetter: 'B+', score4: 3.5, category: 'daicuong' },
      { id: 's-605', code: 'INT3510', name: 'Dự án Công nghệ Thông tin 2', credits: 3, score10: 9.5, scoreLetter: 'A+', score4: 4.0, category: 'chuyennganh' },
    ],
  },
  {
    id: 'sem-y4s1',
    year: 4,
    term: 1,
    name: 'Học kỳ 1 - Năm 4',
    shortName: 'HK1 - Y4',
    academicYear: '2024 - 2025',
    isCompleted: true,
    targetGpa: 3.9,
    subjects: [
      { id: 's-701', code: 'INT4001', name: 'Quản lý dự án phần mềm', credits: 3, score10: 9.0, scoreLetter: 'A+', score4: 4.0, category: 'chuyennganh' },
      { id: 's-702', code: 'INT4005', name: 'Kiến trúc hướng vi dịch vụ (Microservices)', credits: 3, score10: 9.3, scoreLetter: 'A+', score4: 4.0, category: 'tuchon' },
      { id: 's-703', code: 'INT4010', name: 'Chuyên đề Trí tuệ nhân tạo nâng cao', credits: 3, score10: 8.9, scoreLetter: 'A', score4: 3.8, category: 'tuchon' },
      { id: 's-704', code: 'LAW1001', name: 'Pháp luật đại cương', credits: 2, score10: 8.5, scoreLetter: 'A', score4: 3.8, category: 'daicuong' },
      { id: 's-705', code: 'INT4090', name: 'Nghiên cứu khoa học sinh viên', credits: 3, score10: 9.8, scoreLetter: 'A+', score4: 4.0, category: 'thuctap_khoaluan' },
    ],
  },
  {
    id: 'sem-y4s2',
    year: 4,
    term: 2,
    name: 'Học kỳ 2 - Năm 4 (Tốt nghiệp)',
    shortName: 'HK2 - Y4',
    academicYear: '2024 - 2025',
    isCompleted: false,
    targetGpa: 4.0,
    subjects: [
      { id: 's-801', code: 'INT4900', name: 'Khóa luận Tốt nghiệp Đại học (Graduation Thesis)', credits: 10, score10: 9.6, scoreLetter: 'A+', score4: 4.0, category: 'thuctap_khoaluan' },
      { id: 's-802', code: 'INT4905', name: 'Chuyên đề Đổi mới sáng tạo & Khởi nghiệp công nghệ', credits: 3, score10: 9.0, scoreLetter: 'A+', score4: 4.0, category: 'tuchon' },
    ],
  },
];
